# Generated by Django 4.0.5 on 2022-09-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=128)),
                ('fecha_creacion', models.DateField(null=True)),
                ('fecha_entrega', models.DateField(null=True)),
                ('tarea_usuario', models.CharField(default='', max_length=128)),
                ('estado', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=128)),
                ('apellido', models.CharField(default='', max_length=128)),
                ('codigo_usuario', models.CharField(default='', max_length=128)),
                ('password_usuario', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
